/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import javax.swing.JOptionPane;


/**
 *jLabel4
 * @author Usuario
 */
public class Frm_Persona extends javax.swing.JDialog {

   

    /**
     * Creates new form FrmEstujLabel4diante
     */
    public Frm_Persona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
    }

    private void limpiar() {
//        estudianteao.setEstudiante(null);
        cargarTabla();
        txapellido.setText("");
        txnombre.setText("");
        txcedula.setText("");
        txmateria.setText("");
    }

    private void cargarTabla() {
//        mo.setLista(estudianteao.listar());
//        jTable1.setModel(mo);
//        jTable1.updateUI();
    }

    private void guardar() {
//        if (validar()) {
//            estudianteao.getEstudiante().setNombre(txnombre.getText());
//            estudianteao.getEstudiante().setApellido(txapellido.getText());
//            estudianteao.getEstudiante().setCedula(txcedula.getText());
//            estudianteao.getEstudiante().setMateria(txmateria.getText());
//            if (estudianteao.guardar()) {
//                JOptionPane.showMessageDialog(null, "Se ha guardado");
//                this.limpiar();
//            } else {
//                JOptionPane.showMessageDialog(null, "No se ha guardado");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Llene todos los campos");
//        }
    }

    private boolean validar() {
        return (txnombre.getText().trim().length() > 0 && txapellido.getText().trim().length() > 0 && txcedula.getText().trim().length() > 0 && txmateria.getText().trim().length() > 0);
    }

    private void ordenar() {
//        Lista aux;
//        int select = cbdireccion.getSelectedIndex();
//        int select1 = cbmetodo.getSelectedIndex();
//        String atributo = cbatributo.getSelectedItem().toString();
//        if (select1 == 0) {
//            aux = estudianteao.listar().QuisortClase(atributo, 0, estudianteao.listar().tamanio() - 1, select + 1);
//        } else {
//            aux = estudianteao.listar().ShellClase(select + 1, atributo);
//        }
//        mo.setLista(aux);
//        jTable1.setModel(mo);
//        jTable1.updateUI();
    }

    private void buscar() {
//        int select = cbatributobuscar.getSelectedIndex();
//        String atributo = cbatributobuscar.getSelectedItem().toString();
//        Lista aux;
//        if (txbuscar.getText().isEmpty() && select != 0) {
//            JOptionPane.showMessageDialog(null, "Llene el campo necesario");
//        } else {
//            switch (select) {
//                case 0:
//                    aux = estudianteao.listar();
//                    break;
//                case 1:
//                    aux = (Lista) mo.getLista().BusquedaBinariaClase(txbuscar.getText(), atributo);
//                    break;
//
//                case 2:
//                    aux = (Lista) mo.getLista().BusquedaBinariaClase(txbuscar.getText(), atributo);
//                    break;
//
//                case 3:
//                    aux = (Lista) mo.getLista().BusquedaBinariaClase(txbuscar.getText(), atributo);
//                    break;
//
//                default:
//                    aux = mo.getLista();
//            }
//            if (aux == null) {
//                JOptionPane.showMessageDialog(null, "No se ha encontrado el elemento o ordene primero la lista para buscar el elemento");
//            } else {
//                mo.setLista(aux);
//                jTable1.setModel(mo);
//                jTable1.updateUI();
//                txbuscar.setText("");
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txmateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txcedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cbdireccion = new javax.swing.JComboBox<>();
        cbmetodo = new javax.swing.JComboBox<>();
        cbatributo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        cbatributobuscar = new javax.swing.JComboBox<>();
        txbuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 60, 20);
        jPanel1.add(txnombre);
        txnombre.setBounds(80, 20, 110, 30);

        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 50, 20);
        jPanel1.add(txapellido);
        txapellido.setBounds(80, 70, 110, 30);

        jLabel3.setText("Materia");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 50, 20);
        jPanel1.add(txmateria);
        txmateria.setBounds(80, 120, 120, 30);

        jLabel4.setText("Cedula");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 50, 20);
        jPanel1.add(txcedula);
        txcedula.setBounds(80, 170, 110, 30);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 50, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 630, 250);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        cbdireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        jPanel2.add(cbdireccion);
        cbdireccion.setBounds(20, 20, 80, 30);

        cbmetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "quickshort", "Shell" }));
        jPanel2.add(cbmetodo);
        cbmetodo.setBounds(20, 100, 80, 30);

        cbatributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "cedula", "materia" }));
        jPanel2.add(cbatributo);
        cbatributo.setBounds(170, 50, 90, 30);

        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(160, 130, 82, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 20, 320, 190);

        cbatributobuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "todos", "nombre", "apellido", "cedula", "materia" }));
        cbatributobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbatributobuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cbatributobuscar);
        cbatributobuscar.setBounds(40, 230, 90, 30);
        jPanel1.add(txbuscar);
        txbuscar.setBounds(150, 230, 220, 30);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(410, 240, 75, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 750, 550);

        setSize(new java.awt.Dimension(791, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ordenar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbatributobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbatributobuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbatributobuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Persona dialog = new Frm_Persona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbatributo;
    private javax.swing.JComboBox<String> cbatributobuscar;
    private javax.swing.JComboBox<String> cbdireccion;
    private javax.swing.JComboBox<String> cbmetodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txapellido;
    private javax.swing.JTextField txbuscar;
    private javax.swing.JTextField txcedula;
    private javax.swing.JTextField txmateria;
    private javax.swing.JTextField txnombre;
    // End of variables declaration//GEN-END:variables

}
