/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DAO.AdaptadorDao;
import controladorAuto.AutoController;
import javax.swing.JOptionPane;
import vista.tabla.TablaAuto;

/**
 *
 * @author jy
 */
public class FrmAuto extends javax.swing.JFrame {
     
     private AutoController ac = new AutoController();
     private TablaAuto ta = new TablaAuto();

    /**
     * Creates new form FrmCine
     */
    public FrmAuto() {
        initComponents();
        setLocationRelativeTo(null);
        Limpiar();
    }
    
   public void Limpiar (){
        txtColor.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        ac.setAuto(null);
        CargarTabla();
    }
    public void Agregar(){
        
           try {
           ac.getAuto().setColor(txtColor.getText());
           ac.getAuto().setModelo(txtModelo.getText());
           ac.getAuto().setPlaca(txtPlaca.getText());
           ac.guardar();
           Limpiar();
        } catch (Exception e) {
                System.out.println("erro" + e);
        }
    }
    public void CargarTabla(){
            ta.setLista(ac.getLisautos());
            tbl_tabla.setModel(ta);
            tbl_tabla.updateUI();
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jPanel3 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          txtPlaca = new javax.swing.JTextField();
          txtColor = new javax.swing.JTextField();
          btnGuardar = new javax.swing.JButton();
          txtModelo = new javax.swing.JTextField();
          btnCancelar = new javax.swing.JButton();
          jLabel5 = new javax.swing.JLabel();
          jPanel2 = new javax.swing.JPanel();
          txtBusqueda = new javax.swing.JTextField();
          btnBuscar = new javax.swing.JButton();
          jPanel4 = new javax.swing.JPanel();
          cbxOrden = new javax.swing.JComboBox<>();
          jLabel2 = new javax.swing.JLabel();
          cbxTipo = new javax.swing.JComboBox<>();
          jLabel6 = new javax.swing.JLabel();
          cbxMetodo = new javax.swing.JComboBox<>();
          jLabel7 = new javax.swing.JLabel();
          btnOrdenar = new javax.swing.JButton();
          cbxTipoBusqueda = new javax.swing.JComboBox<>();
          jScrollPane2 = new javax.swing.JScrollPane();
          tbl_tabla = new javax.swing.JTable();
          jLabel4 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel1.setBackground(new java.awt.Color(255, 255, 255));
          jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          jPanel1.setForeground(new java.awt.Color(255, 142, 38));
          jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jPanel3.setBackground(new java.awt.Color(255, 255, 255));
          jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informacion del auto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N
          jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          jLabel1.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(51, 51, 51));
          jLabel1.setText("Placa");
          jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 27));

          jLabel3.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel3.setForeground(new java.awt.Color(51, 51, 51));
          jLabel3.setText("Color");
          jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 27));

          txtPlaca.setBackground(new java.awt.Color(255, 255, 255));
          txtPlaca.setForeground(new java.awt.Color(0, 0, 0));
          jPanel3.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, -1));

          txtColor.setBackground(new java.awt.Color(255, 255, 255));
          txtColor.setForeground(new java.awt.Color(0, 0, 0));
          jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 180, -1));

          btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
          btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
          btnGuardar.setText("Guardar");
          btnGuardar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
               }
          });
          jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 30));

          txtModelo.setBackground(new java.awt.Color(255, 255, 255));
          txtModelo.setForeground(new java.awt.Color(0, 0, 0));
          jPanel3.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

          btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
          btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
          btnCancelar.setText("Cancelar");
          jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 30));

          jLabel5.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel5.setForeground(new java.awt.Color(51, 51, 51));
          jLabel5.setText("Modelo");
          jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 27));

          jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 420, 210));

          jPanel2.setBackground(new java.awt.Color(255, 255, 255));
          jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          txtBusqueda.setBackground(new java.awt.Color(255, 255, 255));
          txtBusqueda.setForeground(new java.awt.Color(0, 0, 0));
          txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtBusquedaActionPerformed(evt);
               }
          });
          jPanel2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, -1));

          btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
          btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
          btnBuscar.setText("G");
          jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 30));

          jPanel4.setBackground(new java.awt.Color(255, 255, 255));
          jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
          jPanel4.setForeground(new java.awt.Color(0, 0, 0));
          jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          cbxOrden.setBackground(new java.awt.Color(255, 255, 255));
          cbxOrden.setForeground(new java.awt.Color(0, 0, 0));
          cbxOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCENDENTE", "DESCENDENTE" }));
          jPanel4.add(cbxOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 150, -1));

          jLabel2.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel2.setForeground(new java.awt.Color(51, 51, 51));
          jLabel2.setText("Orden");
          jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 60, 27));

          cbxTipo.setBackground(new java.awt.Color(255, 255, 255));
          cbxTipo.setForeground(new java.awt.Color(0, 0, 0));
          cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo", "Placa", "Color" }));
          cbxTipo.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbxTipoActionPerformed(evt);
               }
          });
          jPanel4.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

          jLabel6.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel6.setForeground(new java.awt.Color(51, 51, 51));
          jLabel6.setText("Tipo");
          jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 27));

          cbxMetodo.setBackground(new java.awt.Color(255, 255, 255));
          cbxMetodo.setForeground(new java.awt.Color(0, 0, 0));
          cbxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shell", "Quicksort" }));
          jPanel4.add(cbxMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, -1));

          jLabel7.setFont(new java.awt.Font("Roboto Condensed, Light", 0, 14)); // NOI18N
          jLabel7.setForeground(new java.awt.Color(51, 51, 51));
          jLabel7.setText("Metodo");
          jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 60, 27));

          btnOrdenar.setBackground(new java.awt.Color(255, 255, 255));
          btnOrdenar.setForeground(new java.awt.Color(0, 0, 0));
          btnOrdenar.setText("Ordenar");
          btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnOrdenarActionPerformed(evt);
               }
          });
          jPanel4.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 110, 30));

          jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 620, 90));

          cbxTipoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
          cbxTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
          cbxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Modelo", "Placa", "Color" }));
          jPanel2.add(cbxTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

          tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jScrollPane2.setViewportView(tbl_tabla);

          jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 170));

          jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 640, 360));

          jLabel4.setFont(new java.awt.Font("Roboto Condensed, Light", 1, 48)); // NOI18N
          jLabel4.setForeground(new java.awt.Color(51, 51, 51));
          jLabel4.setText("DAIMLER");
          jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

          getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 420));

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed

     private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          
          Agregar();
     }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAuto().setVisible(true);
            }
        });
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnBuscar;
     private javax.swing.JButton btnCancelar;
     private javax.swing.JButton btnGuardar;
     private javax.swing.JButton btnOrdenar;
     private javax.swing.JComboBox<String> cbxMetodo;
     private javax.swing.JComboBox<String> cbxOrden;
     private javax.swing.JComboBox<String> cbxTipo;
     private javax.swing.JComboBox<String> cbxTipoBusqueda;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTable tbl_tabla;
     private javax.swing.JTextField txtBusqueda;
     private javax.swing.JTextField txtColor;
     private javax.swing.JTextField txtModelo;
     private javax.swing.JTextField txtPlaca;
     // End of variables declaration//GEN-END:variables
}
